/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.davshaw.Gui.User;

import javax.swing.JOptionPane;

import org.davshaw.Controller.TeamDepositController;
import org.davshaw.Controller.UserController;
import org.davshaw.External.Checker;
import org.davshaw.External.ResultPack;
import org.davshaw.Service.Team.GetTeamReportAsText;

/**
 *
 * @author Asus
 */
public class TeamDepositPage extends javax.swing.JFrame {

    /**
     * Creates new form TeamDeposit
     */
    public TeamDepositPage() {
        initComponents();
    }
    
    public void setUserDni(Integer userDni) {
        this.userDni = userDni;
    }
    
    public void executePostStart() {
        String msg = GetTeamReportAsText.getText(this.userDni);
        this.showTeamsTextArea.setText(msg);
        this.showTeamsTextArea.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        showTeamsTextArea = new javax.swing.JTextArea();
        teamIdTextField = new javax.swing.JTextField();
        amountTextField = new javax.swing.JTextField();
        backbutton = new javax.swing.JButton();
        teamDepositButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        showTeamsTextArea.setColumns(20);
        showTeamsTextArea.setRows(5);
        jScrollPane1.setViewportView(showTeamsTextArea);

        teamIdTextField.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N

        amountTextField.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N

        backbutton.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
        backbutton.setText("Back");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        teamDepositButton.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
        teamDepositButton.setText("Deposit");
        teamDepositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamDepositButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teamIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(141, 141, 141)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(273, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teamDepositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(261, 261, 261))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(teamIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(teamDepositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        UserPage frame = new UserPage();
        frame.setUserDni(this.userDni);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbuttonActionPerformed

    private void teamDepositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamDepositButtonActionPerformed
        
        String teamIdStr = this.teamIdTextField.getText();
        String amountStr = this.amountTextField.getText();

        if (Checker.isDigit(amountStr) && Checker.isDigit(amountStr)) {

            Integer teamId = Integer.valueOf(teamIdStr);
            Double amount = Double.valueOf(amountStr);
            Integer logId = UserController.getLogId(this.userDni, teamId).getResult();

            ResultPack<Boolean> r1 = TeamDepositController.deposit(logId, amount);

            if (r1.getOkay()) {
                JOptionPane.showMessageDialog(this, r1.getMessageFormatted(), "Team deposit",JOptionPane.INFORMATION_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(this, r1.getMessageFormatted(), "Team deposit",JOptionPane.ERROR_MESSAGE);
            }


        }
        else {
            JOptionPane.showMessageDialog(this, "Invalid team id / amount", "Team deposit", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_teamDepositButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeamDepositPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeamDepositPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeamDepositPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeamDepositPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeamDepositPage().setVisible(true);
            }
        });
    }

    private Integer userDni;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountTextField;
    private javax.swing.JButton backbutton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea showTeamsTextArea;
    private javax.swing.JButton teamDepositButton;
    private javax.swing.JTextField teamIdTextField;
    // End of variables declaration//GEN-END:variables
}
