/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.davshaw.view.swing;

import java.sql.SQLException;

import javax.swing.JOptionPane;

import org.davshaw.classes.Hospital;
import org.davshaw.classes.RequestQueue;
import org.davshaw.external.DataBase;
import org.davshaw.external.QueueFromDatabase;
import org.davshaw.resources.TestCase;

/**
 *
 * @author Asus
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     * @throws SQLException
     */
    public MainWindow() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.tester = new TestCase();
        this.hospital = new Hospital(10000);
        DataBase db = this.tester.getDatabase();
        RequestQueue queue = new QueueFromDatabase(db).getRequestQueue();
        this.hospital.actualizarCola(queue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContainer = new javax.swing.JPanel();
        enterNewRequest = new javax.swing.JButton();
        assistRequest = new javax.swing.JButton();
        viewRequest = new javax.swing.JButton();
        changeRequestPriority = new javax.swing.JButton();
        toExit = new javax.swing.JButton();
        deleteData = new javax.swing.JButton();
        testZone = new javax.swing.JButton();
        testCaseNo1 = new javax.swing.JButton();
        testCaseNo2 = new javax.swing.JButton();
        testCaseNo3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainContainer.setBackground(new java.awt.Color(102, 153, 255));

        enterNewRequest.setBackground(new java.awt.Color(153, 255, 102));
        enterNewRequest.setText("Agregar solicitud");
        enterNewRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterNewRequestActionPerformed(evt);
            }
        });

        assistRequest.setBackground(new java.awt.Color(153, 255, 255));
        assistRequest.setText("Atender solicitud");
        assistRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assistRequestActionPerformed(evt);
            }
        });

        viewRequest.setBackground(new java.awt.Color(255, 153, 255));
        viewRequest.setText("Ver solicitudes");
        viewRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRequestActionPerformed(evt);
            }
        });

        changeRequestPriority.setBackground(new java.awt.Color(255, 255, 51));
        changeRequestPriority.setText("Cambiar prioridad");
        changeRequestPriority.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeRequestPriorityActionPerformed(evt);
            }
        });

        toExit.setBackground(new java.awt.Color(255, 153, 153));
        toExit.setText("SALIR");
        toExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toExitActionPerformed(evt);
            }
        });

        deleteData.setBackground(new java.awt.Color(255, 27, 41));
        deleteData.setText("Borrar datos");
        deleteData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDataActionPerformed(evt);
            }
        });

        testZone.setBackground(new java.awt.Color(102, 153, 255));
        testZone.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        testZone.setText("🡓 PRUEBAS 🡓");
        testZone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testZoneActionPerformed(evt);
            }
        });

        testCaseNo1.setBackground(new java.awt.Color(102, 255, 102));
        testCaseNo1.setText("Caso No. 1");
        testCaseNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testCaseNo1ActionPerformed(evt);
            }
        });

        testCaseNo2.setBackground(new java.awt.Color(102, 255, 102));
        testCaseNo2.setText("Caso No. 2");
        testCaseNo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testCaseNo2ActionPerformed(evt);
            }
        });

        testCaseNo3.setBackground(new java.awt.Color(102, 255, 102));
        testCaseNo3.setText("Caso No. 3");
        testCaseNo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testCaseNo3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainContainerLayout = new javax.swing.GroupLayout(mainContainer);
        mainContainer.setLayout(mainContainerLayout);
        mainContainerLayout.setHorizontalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainerLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(toExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(95, 95, 95))
            .addGroup(mainContainerLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(changeRequestPriority, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(assistRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enterNewRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(testCaseNo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(testCaseNo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(testCaseNo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(testZone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainContainerLayout.setVerticalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainerLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(enterNewRequest)
                .addGap(18, 18, 18)
                .addComponent(assistRequest)
                .addGap(18, 18, 18)
                .addComponent(viewRequest)
                .addGap(18, 18, 18)
                .addComponent(changeRequestPriority)
                .addGap(18, 18, 18)
                .addComponent(deleteData)
                .addGap(18, 18, 18)
                .addComponent(toExit)
                .addGap(40, 40, 40)
                .addComponent(testZone)
                .addGap(18, 18, 18)
                .addComponent(testCaseNo1)
                .addGap(18, 18, 18)
                .addComponent(testCaseNo2)
                .addGap(12, 12, 12)
                .addComponent(testCaseNo3)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterNewRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterNewRequestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterNewRequestActionPerformed

    private void assistRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assistRequestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assistRequestActionPerformed

    private void viewRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRequestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewRequestActionPerformed

    private void changeRequestPriorityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeRequestPriorityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeRequestPriorityActionPerformed

    private void toExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_toExitActionPerformed

    private void deleteDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDataActionPerformed
        this.tester.deleteData();
        JOptionPane.showMessageDialog(null, "Se han borrado todas las solicitudes","Solicitudes" ,JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_deleteDataActionPerformed

    private void testZoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testZoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testZoneActionPerformed

    private void testCaseNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testCaseNo1ActionPerformed
        this.tester.testCaseN1();
        JOptionPane.showMessageDialog(null, "El caso 1 se ha ejecutado","Pruebas" ,JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_testCaseNo1ActionPerformed

    private void testCaseNo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testCaseNo2ActionPerformed
        this.tester.testCaseN2();
        JOptionPane.showMessageDialog(null, "El caso 2 se ha ejecutado","Pruebas" ,JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_testCaseNo2ActionPerformed

    private void testCaseNo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testCaseNo3ActionPerformed
        this.tester.testCaseN3();
        JOptionPane.showMessageDialog(null, "El caso 3 se ha ejecutado","Pruebas" ,JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_testCaseNo3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainWindow().setVisible(true);
                } catch (SQLException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private TestCase tester;
    private javax.swing.JButton assistRequest;
    private javax.swing.JButton changeRequestPriority;
    private javax.swing.JButton deleteData;
    private javax.swing.JButton enterNewRequest;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JButton testCaseNo1;
    private javax.swing.JButton testCaseNo2;
    private javax.swing.JButton testCaseNo3;
    private javax.swing.JButton testZone;
    private javax.swing.JButton toExit;
    private javax.swing.JButton viewRequest;
    private Hospital hospital;
    // End of variables declaration//GEN-END:variables
}