/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.davshaw.view.swing;

import java.sql.SQLException;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

import org.davshaw.classes.Hospital;
import org.davshaw.classes.RequestQueue;
import org.davshaw.external.DataBase;
import org.davshaw.external.QueueFromDatabase;
import org.davshaw.resources.TestCase;

/**
 *
 * @author Asus
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     * @throws SQLException
     */
    public MainWindow() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.tester = new TestCase();
        this.hospital = new Hospital(10000);
    }

    private void actualizarHospital() throws SQLException
    {
        DataBase db = this.tester.getDatabase();
        db.connect();
        RequestQueue queue = new QueueFromDatabase(db).getRequestQueue();
        this.hospital.actualizarCola(queue);
        db.disconnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        showMessageAsDialog = new javax.swing.JDialog();
        mainContainer = new javax.swing.JPanel();
        enterNewRequest = new javax.swing.JButton();
        assistRequest = new javax.swing.JButton();
        viewRequest = new javax.swing.JButton();
        changeRequestPriority = new javax.swing.JButton();
        toExit = new javax.swing.JButton();
        deleteData = new javax.swing.JButton();
        testZone = new javax.swing.JButton();
        testCaseNo1 = new javax.swing.JButton();
        testCaseNo2 = new javax.swing.JButton();
        testCaseNo3 = new javax.swing.JButton();

        javax.swing.GroupLayout showMessageAsDialogLayout = new javax.swing.GroupLayout(showMessageAsDialog.getContentPane());
        showMessageAsDialog.getContentPane().setLayout(showMessageAsDialogLayout);
        showMessageAsDialogLayout.setHorizontalGroup(
            showMessageAsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        showMessageAsDialogLayout.setVerticalGroup(
            showMessageAsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        this.showMessageAsDialog.setTitle("Solicictudes totales");
        this.showMessageAsDialog.setModal(true);
        this.showMessageAsDialog.setSize(400, 300);


        mainContainer.setBackground(new java.awt.Color(102, 153, 255));

        enterNewRequest.setBackground(new java.awt.Color(153, 255, 102));
        enterNewRequest.setText("Agregar solicitud");
        enterNewRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterNewRequestActionPerformed(evt);
            }
        });

        assistRequest.setBackground(new java.awt.Color(153, 255, 255));
        assistRequest.setText("Atender solicitud");
        assistRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assistRequestActionPerformed(evt);
            }
        });

        viewRequest.setBackground(new java.awt.Color(255, 153, 255));
        viewRequest.setText("Ver solicitudes");
        viewRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRequestActionPerformed(evt);
            }
        });

        changeRequestPriority.setBackground(new java.awt.Color(255, 255, 51));
        changeRequestPriority.setText("Cambiar prioridad");
        changeRequestPriority.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeRequestPriorityActionPerformed(evt);
            }
        });

        toExit.setBackground(new java.awt.Color(255, 153, 153));
        toExit.setText("SALIR");
        toExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toExitActionPerformed(evt);
            }
        });

        deleteData.setBackground(new java.awt.Color(255, 27, 41));
        deleteData.setText("Borrar datos");
        deleteData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    deleteDataActionPerformed(evt);
                } catch (SQLException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });

        testZone.setBackground(new java.awt.Color(102, 153, 255));
        testZone.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        testZone.setText("🡓 PRUEBAS 🡓");
        testZone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testZoneActionPerformed(evt);
            }
        });

        testCaseNo1.setBackground(new java.awt.Color(102, 255, 102));
        testCaseNo1.setText("Caso No. 1");
        testCaseNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    testCaseNo1ActionPerformed(evt);
                } catch (SQLException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });

        testCaseNo2.setBackground(new java.awt.Color(102, 255, 102));
        testCaseNo2.setText("Caso No. 2");
        testCaseNo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    testCaseNo2ActionPerformed(evt);
                } catch (SQLException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });

        testCaseNo3.setBackground(new java.awt.Color(102, 255, 102));
        testCaseNo3.setText("Caso No. 3");
        testCaseNo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    testCaseNo3ActionPerformed(evt);
                } catch (SQLException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });

        javax.swing.GroupLayout mainContainerLayout = new javax.swing.GroupLayout(mainContainer);
        mainContainer.setLayout(mainContainerLayout);
        mainContainerLayout.setHorizontalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainerLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(toExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(95, 95, 95))
            .addGroup(mainContainerLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(changeRequestPriority, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(assistRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enterNewRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(testCaseNo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(testCaseNo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(testCaseNo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(testZone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainContainerLayout.setVerticalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainerLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(enterNewRequest)
                .addGap(18, 18, 18)
                .addComponent(assistRequest)
                .addGap(18, 18, 18)
                .addComponent(viewRequest)
                .addGap(18, 18, 18)
                .addComponent(changeRequestPriority)
                .addGap(18, 18, 18)
                .addComponent(deleteData)
                .addGap(18, 18, 18)
                .addComponent(toExit)
                .addGap(40, 40, 40)
                .addComponent(testZone)
                .addGap(18, 18, 18)
                .addComponent(testCaseNo1)
                .addGap(18, 18, 18)
                .addComponent(testCaseNo2)
                .addGap(12, 12, 12)
                .addComponent(testCaseNo3)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void enterNewRequestActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void assistRequestActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void viewRequestActionPerformed(java.awt.event.ActionEvent evt) {  
        // Crear TextArea
        JTextArea textArea = new JTextArea(this.hospital.visualizarSolicitudes());
        textArea.setLineWrap(true); // Habilitar ajuste de línea
        textArea.setWrapStyleWord(true); // Ajustar palabras enteras

        // Crear Scrollpane
        JScrollPane scrollPane = new JScrollPane(textArea);

        // Configurar el ScrollPane
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS); // Mostrar la barra de desplazamiento vertical siempre

        // Crear el diálogo
        JDialog dialog = new JDialog();
        dialog.setTitle("Visualización de Solicitudes");
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE); // Configurar acción de cierre
        dialog.setSize(400, 300);
        dialog.add(scrollPane); // Agregar el JScrollPane al diálogo

        // Mostrar el diálogo
        dialog.setVisible(true);
    }                                           

    private void changeRequestPriorityActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void toExitActionPerformed(java.awt.event.ActionEvent evt) {                                       
        System.exit(0);
    }                                      

    private void deleteDataActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {                                           
        this.tester.deleteData();
        this.actualizarHospital();
        JOptionPane.showMessageDialog(null, "Se han borrado todas las solicitudes","Solicitudes" ,JOptionPane.WARNING_MESSAGE);
    }                                          

    private void testZoneActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void testCaseNo1ActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {                                            
        this.tester.deleteData();
        this.tester.testCaseN1();
        this.actualizarHospital();
        JOptionPane.showMessageDialog(null, "El caso 1 se ha ejecutado","Pruebas" ,JOptionPane.INFORMATION_MESSAGE);
    }                                           

    private void testCaseNo2ActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {                                            
        this.tester.deleteData();
        this.tester.testCaseN2();
        this.actualizarHospital();
        JOptionPane.showMessageDialog(null, "El caso 2 se ha ejecutado","Pruebas" ,JOptionPane.INFORMATION_MESSAGE);
    }                                           

    private void testCaseNo3ActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {                                            
        this.tester.deleteData();
        this.tester.testCaseN3();
        this.actualizarHospital();
        JOptionPane.showMessageDialog(null, "El caso 3 se ha ejecutado","Pruebas" ,JOptionPane.INFORMATION_MESSAGE);
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainWindow().setVisible(true);
                } catch (SQLException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });
    }

    private TestCase tester;
    private Hospital hospital;
    // Variables declaration - do not modify                     
    private javax.swing.JButton assistRequest;
    private javax.swing.JButton changeRequestPriority;
    private javax.swing.JButton deleteData;
    private javax.swing.JButton enterNewRequest;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JDialog showMessageAsDialog;
    private javax.swing.JButton testCaseNo1;
    private javax.swing.JButton testCaseNo2;
    private javax.swing.JButton testCaseNo3;
    private javax.swing.JButton testZone;
    private javax.swing.JButton toExit;
    private javax.swing.JButton viewRequest;
    // End of variables declaration                   
}