#Hoy aprenderemos: Keywords de Python3

print("¡Hola! Este archivo es para contener las 28 palabras reservardas/Keywords de Pyton")
print("")
print("and")
print("del")
print("for")
print("is")
print("raise")
print("assert")
print("if")
print("else")
print("elif")
print("from")
print("lambda")
print("return")
print("break")
print("global")
print("not")
print("try")
print("class")
print("except")
print("or")
print("while")
print("continue")
print("except")
print("import")
print("yield")
print("def")
print("finally")
print("in")
print("print")
