/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.davshaw.Gui.Admin.Account;

import javax.swing.JOptionPane;
import org.davshaw.Controller.AccountController;
import org.davshaw.Controller.UserController;
import org.davshaw.External.Checker;
import org.davshaw.External.ResultPack;
import org.davshaw.Gui.Admin.Admin.AdminPage;
import org.davshaw.Gui.Admin.User.SeeLoansPage;

/**
 *
 * @author Asus
 */
public class AccountPage extends javax.swing.JFrame {

  /**
   * Creates new form AccountPage
   */
  public AccountPage() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        createAccountButton = new javax.swing.JButton();
        viewHistoryButton = new javax.swing.JButton();
        deleteAccountButton = new javax.swing.JButton();
        withdrawBalanceButton = new javax.swing.JButton();
        addBalanceButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backButton.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        createAccountButton.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
        createAccountButton.setText("Create Account");
        createAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountButtonActionPerformed(evt);
            }
        });

        viewHistoryButton.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
        viewHistoryButton.setText("View History");
        viewHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewHistoryButtonActionPerformed(evt);
            }
        });

        deleteAccountButton.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
        deleteAccountButton.setText("Delete Account");
        deleteAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccountButtonActionPerformed(evt);
            }
        });

        withdrawBalanceButton.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
        withdrawBalanceButton.setText("W.Draw Balance");
        withdrawBalanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawBalanceButtonActionPerformed(evt);
            }
        });

        addBalanceButton.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
        addBalanceButton.setText("Add Balance");
        addBalanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBalanceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addBalanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(170, 170, 170)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(withdrawBalanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewHistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(withdrawBalanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addBalanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(createAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewHistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(156, 156, 156))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void deleteAccountButtonActionPerformed(
    java.awt.event.ActionEvent evt
  ) {//GEN-FIRST:event_deleteAccountButtonActionPerformed
    String dniStr = JOptionPane.showInputDialog(
      this,
      "Enter user Dni: ",
      "Delete Account",
      JOptionPane.PLAIN_MESSAGE
    );
    if (dniStr != null) {
      if (Checker.isDigit(dniStr)) {
        int dni = Integer.parseInt(dniStr);
        ResultPack<Boolean> r1 = UserController.userExist(dni);
        if (r1.getResult()) {
          ResultPack<Boolean> r2 = AccountController.deleteAccount(dni);
          String message = String.format(
            "Account deleted successfully: %s\nServer return: %s\nMessage: %s",
            r2.getOkay(),
            r2.getResult(),
            r2.getMessage()
          );

          JOptionPane.showMessageDialog(
            this,
            message,
            "Delete Account",
            JOptionPane.INFORMATION_MESSAGE
          );
        } else {
          JOptionPane.showMessageDialog(
            this,
            r1.getMessage(),
            "Delete account",
            JOptionPane.ERROR_MESSAGE
          );
        }
      } else {
        JOptionPane.showMessageDialog(
          this,
          "Invalid Dni.",
          "Delete Account",
          JOptionPane.ERROR_MESSAGE
        );
      }
    }
  }//GEN-LAST:event_deleteAccountButtonActionPerformed

  private void createAccountButtonActionPerformed(
    java.awt.event.ActionEvent evt
  ) {//GEN-FIRST:event_createAccountButtonActionPerformed
    
    String dniStr = JOptionPane.showInputDialog(
      this,
      "Enter user Dni: ",
      "Create Account",
      JOptionPane.PLAIN_MESSAGE
    );
    if (dniStr != null) {
      if (Checker.isDigit(dniStr)) {
        int dni = Integer.parseInt(dniStr);
        ResultPack<Boolean> r1 = AccountController.createAccount(dni);
        if (r1.getResult()) {

          System.out.println("Se ejecutó xd");
          System.out.println(r1);
          System.out.println("Search this");
          String message = String.format(
            "Account created successfully: %s\nServer return: %s\nMessage: %s",
            r1.getOkay(),
            r1.getResult(),
            r1.getMessage()
          );

          JOptionPane.showMessageDialog(
            this,
            r1.getMessage(),
            "Create Account",
            JOptionPane.ERROR_MESSAGE
          );

        } else {
          JOptionPane.showMessageDialog(
            this,
            r1.getMessage(),
            "Create Account",
            JOptionPane.ERROR_MESSAGE
          );
        }
      } else {
        JOptionPane.showMessageDialog(
          this,
          "Invalid Dni.",
          "Create Account",
          JOptionPane.ERROR_MESSAGE
        );
      }
    }

  }//GEN-LAST:event_createAccountButtonActionPerformed

  private void editAccountButtonActionPerformed(
    java.awt.event.ActionEvent evt
  ) {//GEN-FIRST:event_editAccountButtonActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_editAccountButtonActionPerformed

  private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
    AdminPage frame = new AdminPage();
    frame.setVisible(true);
    this.dispose();
  }//GEN-LAST:event_backButtonActionPerformed

  private void addBalanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBalanceButtonActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_addBalanceButtonActionPerformed

  private void withdrawBalanceButtonActionPerformed(
    java.awt.event.ActionEvent evt
  ) {//GEN-FIRST:event_withdrawBalanceButtonActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_withdrawBalanceButtonActionPerformed

  private void viewHistoryButtonActionPerformed(
    java.awt.event.ActionEvent evt
  ) {//GEN-FIRST:event_viewHistoryButtonActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_viewHistoryButtonActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger
        .getLogger(AccountPage.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger
        .getLogger(AccountPage.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger
        .getLogger(AccountPage.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger
        .getLogger(AccountPage.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
      new Runnable() {
        public void run() {
          new AccountPage().setVisible(true);
        }
      }
    );
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBalanceButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton createAccountButton;
    private javax.swing.JButton deleteAccountButton;
    private javax.swing.JButton viewHistoryButton;
    private javax.swing.JButton withdrawBalanceButton;
    // End of variables declaration//GEN-END:variables
}
