package org.davshaw.Gui.Admin.Account;

import org.davshaw.Gui.Admin.Admin.AdminPage;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Asus
 */
public class AccountPage extends javax.swing.JFrame {

  /**
   * Creates new form AccountPage
   */
  public AccountPage() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    jButton5 = new javax.swing.JButton();
    deleteAccountButton = new javax.swing.JButton();
    editAccountButton = new javax.swing.JButton();
    backButton = new javax.swing.JButton();
    addBalanceButton = new javax.swing.JButton();
    withdrawBalanceButton = new javax.swing.JButton();
    viewHistoryButton = new javax.swing.JButton();

    jButton5.setText("Add Balance");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    deleteAccountButton.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
    deleteAccountButton.setText("Delete Account");
    deleteAccountButton.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          deleteAccountButtonActionPerformed(evt);
        }
      }
    );

    editAccountButton.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
    editAccountButton.setText("Edit Account");
    editAccountButton.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          editAccountButtonActionPerformed(evt);
        }
      }
    );

    backButton.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
    backButton.setText("Back");
    backButton.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          backButtonActionPerformed(evt);
        }
      }
    );

    addBalanceButton.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
    addBalanceButton.setText("Add Balance");
    addBalanceButton.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          addBalanceButtonActionPerformed(evt);
        }
      }
    );

    withdrawBalanceButton.setFont(
      new java.awt.Font("Microsoft Yi Baiti", 1, 20)
    ); // NOI18N
    withdrawBalanceButton.setText("W.draw Balance");
    withdrawBalanceButton.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          withdrawBalanceButtonActionPerformed(evt);
        }
      }
    );

    viewHistoryButton.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
    viewHistoryButton.setText("View History");
    viewHistoryButton.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          viewHistoryButtonActionPerformed(evt);
        }
      }
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addGap(120, 120, 120)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(
                  deleteAccountButton,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  150,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  editAccountButton,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  150,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  backButton,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  150,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(197, 197, 197)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(
                  viewHistoryButton,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  150,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  withdrawBalanceButton,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  150,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  addBalanceButton,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  150,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addContainerGap(120, Short.MAX_VALUE)
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addGap(70, 70, 70)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(
                  deleteAccountButton,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  60,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  addBalanceButton,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  60,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(76, 76, 76)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(
                  editAccountButton,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  60,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  withdrawBalanceButton,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  60,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(77, 77, 77)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(
                  backButton,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  60,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  viewHistoryButton,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  60,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addContainerGap(70, Short.MAX_VALUE)
        )
    );

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void backButtonActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_backButtonActionPerformed
    AdminPage frame = new AdminPage();
    frame.setVisible(true);

    this.dispose();
  } //GEN-LAST:event_backButtonActionPerformed

  private void deleteAccountButtonActionPerformed(
    java.awt.event.ActionEvent evt
  ) { //GEN-FIRST:event_deleteAccountButtonActionPerformed
    // TODO add your handling code here:
  } //GEN-LAST:event_deleteAccountButtonActionPerformed

  private void editAccountButtonActionPerformed(
    java.awt.event.ActionEvent evt
  ) { //GEN-FIRST:event_editAccountButtonActionPerformed
    // TODO add your handling code here:
  } //GEN-LAST:event_editAccountButtonActionPerformed

  private void addBalanceButtonActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_addBalanceButtonActionPerformed
    // TODO add your handling code here:
  } //GEN-LAST:event_addBalanceButtonActionPerformed

  private void withdrawBalanceButtonActionPerformed(
    java.awt.event.ActionEvent evt
  ) { //GEN-FIRST:event_withdrawBalanceButtonActionPerformed
    // TODO add your handling code here:
  } //GEN-LAST:event_withdrawBalanceButtonActionPerformed

  private void viewHistoryButtonActionPerformed(
    java.awt.event.ActionEvent evt
  ) { //GEN-FIRST:event_viewHistoryButtonActionPerformed
    // TODO add your handling code here:
  } //GEN-LAST:event_viewHistoryButtonActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger
        .getLogger(AccountPage.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger
        .getLogger(AccountPage.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger
        .getLogger(AccountPage.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger
        .getLogger(AccountPage.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
      new Runnable() {
        public void run() {
          new AccountPage().setVisible(true);
        }
      }
    );
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addBalanceButton;
  private javax.swing.JButton backButton;
  private javax.swing.JButton deleteAccountButton;
  private javax.swing.JButton editAccountButton;
  private javax.swing.JButton jButton5;
  private javax.swing.JButton viewHistoryButton;
  private javax.swing.JButton withdrawBalanceButton;
  // End of variables declaration//GEN-END:variables
}
