/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.davshaw.Gui.Admin.User;

import java.util.List;

import javax.swing.JOptionPane;

import org.davshaw.Controller.AccountController;
import org.davshaw.Controller.TeamLoanController;
import org.davshaw.Controller.UserController;
import org.davshaw.External.Checker;
import org.davshaw.External.ResultPack;
import org.davshaw.Model.pureentities.User;
import org.davshaw.Service.Loan.getLoanReportAsText;

/**
 *
 * @author Asus
 */

 

public class UserPage extends javax.swing.JFrame {

    /**
     * Creates new form UserPage
     */
    public UserPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        createUserButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        deleteUserButton = new javax.swing.JButton();
        editUserButton = new javax.swing.JButton();
        viewLoansButton = new javax.swing.JButton();
        viewTeamsButton = new javax.swing.JButton();
        viewHistoryButton = new javax.swing.JButton();
        viewDebtsButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createUserButton.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
        createUserButton.setText("Create User");
        createUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserButtonActionPerformed(evt);
            }
        });

        exitButton.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        deleteUserButton.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
        deleteUserButton.setText("Delete User");
        deleteUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserButtonActionPerformed(evt);
            }
        });

        editUserButton.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
        editUserButton.setText("Edit User");
        editUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserButtonActionPerformed(evt);
            }
        });

        viewLoansButton.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
        viewLoansButton.setText("View Loans");
        viewLoansButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLoansButtonActionPerformed(evt);
            }
        });

        viewTeamsButton.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
        viewTeamsButton.setText("View Teams");
        viewTeamsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTeamsButtonActionPerformed(evt);
            }
        });

        viewHistoryButton.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
        viewHistoryButton.setText("View History");
        viewHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewHistoryButtonActionPerformed(evt);
            }
        });

        viewDebtsButton.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
        viewDebtsButton.setText("View Debts");
        viewDebtsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDebtsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deleteUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewLoansButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewTeamsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewHistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewDebtsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewLoansButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewTeamsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewHistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewDebtsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserButtonActionPerformed
        // TODO add your handling code here:
        // Create instance of another frame
        CreateUser newFrame = new CreateUser();
        newFrame.setVisible(true);
        // Clouse this frame
        dispose();
    }//GEN-LAST:event_createUserButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void deleteUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserButtonActionPerformed
        // TODO add your handling code here:
        //Enter dni
        String dniString = JOptionPane.showInputDialog(this, "User DNI:", "Delete User", JOptionPane.INFORMATION_MESSAGE);
        

        if(dniString != null)
        {
            if(Checker.isDigit(dniString))
            {
                int dni = Integer.parseInt(dniString);
                ResultPack<Boolean> result = UserController.deleteUser(dni);
                String message = String.format("User deleted successfully: %s\nServer return: %s\nMessage: %s", result.getOkay(), result.getResult(), result.getMessage());
                JOptionPane.showMessageDialog(this, message, "Delete User", JOptionPane.INFORMATION_MESSAGE);
            }
    
            else
            {
                JOptionPane.showMessageDialog(this, "Invalid Dni", "Delete User", JOptionPane.INFORMATION_MESSAGE);
            }
        }


    }//GEN-LAST:event_deleteUserButtonActionPerformed

    private void editUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserButtonActionPerformed
        // TODO add your handling code here:
        String dniString = JOptionPane.showInputDialog(this, "User DNI:", "Delete User", JOptionPane.INFORMATION_MESSAGE);
        if(dniString != null) {
            if(Checker.isDigit(dniString)) {
                int dni = Integer.parseInt(dniString);
                //Check if exists
                ResultPack<Boolean> result = UserController.userExist(dni);
                if(result.getResult()) {

                    //Get result pack from get user
                    ResultPack<User> getUserResult = UserController.getUser(dni);

                    //Instanciar la nueva ventana
                    EditUser frame = new EditUser();
                    frame.setUserDni(dni);
                    frame.setUser(getUserResult.getResult());
                    frame.setVisible(true);
                    dispose();
                }

                else {
                    JOptionPane.showMessageDialog(this, result.getMessage(), "Edit User", JOptionPane.ERROR_MESSAGE);
                }


            }
    
            else
            {
                JOptionPane.showMessageDialog(this, "Invalid Dni", "Delete User", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_editUserButtonActionPerformed

    private void viewLoansButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLoansButtonActionPerformed
        // TODO add your handling code here:
        String userDniString = JOptionPane.showInputDialog(this, "Enter user DNI: ", "View Loan", JOptionPane.INFORMATION_MESSAGE);
        if(Checker.isDigit(userDniString)) {
            ResultPack<Boolean> result = UserController.userExist(Integer.valueOf(userDniString));
            if(result.getResult()) {
                viewLoansPage frame = new viewLoansPage();

                ResultPack<List<Integer>> r2 = TeamLoanController.getLoanReport(Integer.valueOf(userDniString));
                String message = getLoanReportAsText.getText(r2.getResult());
                frame.setMsg(message);
                frame.setUserDni(Integer.valueOf(userDniString));
                frame.setVisible(true);
                dispose();
            }
            else {
                JOptionPane.showMessageDialog(this, "Invalid dni.", "View Loans.", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_viewLoansButtonActionPerformed

    private void viewTeamsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTeamsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewTeamsButtonActionPerformed

    private void viewHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewHistoryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewHistoryButtonActionPerformed

    private void viewDebtsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDebtsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewDebtsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createUserButton;
    private javax.swing.JButton deleteUserButton;
    private javax.swing.JButton editUserButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton viewDebtsButton;
    private javax.swing.JButton viewHistoryButton;
    private javax.swing.JButton viewLoansButton;
    private javax.swing.JButton viewTeamsButton;
    // End of variables declaration//GEN-END:variables
}
