/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.davshaw.Gui.User;

import javax.swing.JOptionPane;

import org.davshaw.Controller.AccountController;
import org.davshaw.Controller.AccountTransferController;
import org.davshaw.Controller.UserController;
import org.davshaw.External.Checker;
import org.davshaw.External.ResultPack;

/**
 *
 * @author Asus
 */
public class UserPage extends javax.swing.JFrame {

    /**
     * Creates new form UserPage
     */
    public UserPage() {
        initComponents();
    }

    public void executePostStart() {

    }

    public void setUserDni(Integer userDni) {
        this.userDni = userDni;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transferButton = new javax.swing.JButton();
        joinTeamButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        myTeamsButton = new javax.swing.JButton();
        leaveTeamButton = new javax.swing.JButton();
        changePasswordButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        transferButton.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
        transferButton.setText("Transfer");
        transferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferButtonActionPerformed(evt);
            }
        });

        joinTeamButton.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
        joinTeamButton.setText("Join Team");
        joinTeamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinTeamButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        myTeamsButton.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
        myTeamsButton.setText("My Teams");
        myTeamsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myTeamsButtonActionPerformed(evt);
            }
        });

        leaveTeamButton.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
        leaveTeamButton.setText("Leave Team");
        leaveTeamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveTeamButtonActionPerformed(evt);
            }
        });

        changePasswordButton.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
        changePasswordButton.setText("Change Pass");
        changePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(myTeamsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transferButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(joinTeamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(leaveTeamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(changePasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(joinTeamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myTeamsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leaveTeamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changePasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferButtonActionPerformed
        
        String destinationUserDni = JOptionPane
        .showInputDialog(
            this,
            "Enter destination user dni: ",
            "Transfer",
            JOptionPane.QUESTION_MESSAGE);

        String amount = JOptionPane
        .showInputDialog(
            this,
            "Enter the amount: ",
            "Transfer",
            JOptionPane.QUESTION_MESSAGE);

        if(Checker.isDigit(destinationUserDni) && Checker.isDigit(amount)) {

            Integer destinationUserDniInt = Integer.parseInt(destinationUserDni);
            Double amountDouble = Double.parseDouble(amount);

            ResultPack<Boolean> r1 = AccountController.accountExist(destinationUserDniInt);
            
            if(r1.getResult()) {

                ResultPack<Boolean> r2 = AccountTransferController.transfer(this.userDni, destinationUserDniInt, amountDouble);
                JOptionPane.showMessageDialog(this, r2.getMessageFormatted(), "Transfer", JOptionPane.INFORMATION_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(this, r1.getMessageFormatted(), "Transfer", JOptionPane.ERROR_MESSAGE);
            }
            

        }
        else {
            JOptionPane.showMessageDialog(this, "Invalid number.", "Transfer", JOptionPane.ERROR_MESSAGE);
        }
        

    }//GEN-LAST:event_transferButtonActionPerformed

    private void leaveTeamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveTeamButtonActionPerformed
        
        String teamId = JOptionPane.showInputDialog(this, "Enter team id:", "Leave team", JOptionPane.QUESTION_MESSAGE);

        if(Checker.isDigit(teamId)) {

            ResultPack<Boolean> r1 = UserController.leaveTeam(this.userDni, Integer.parseInt(teamId));
            JOptionPane.showMessageDialog(this, r1.getMessageFormatted(), "Transfer", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(this, "Invalid number.", "Transfer", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_leaveTeamButtonActionPerformed

    private void joinTeamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinTeamButtonActionPerformed
        JoinTeamPage frame = new JoinTeamPage();
        frame.setUserDni(this.userDni);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_joinTeamButtonActionPerformed

    private void myTeamsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myTeamsButtonActionPerformed
        ViewTeamPage frame = new ViewTeamPage();
        frame.setUserDni(this.userDni);
        frame.executePostStart();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_myTeamsButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        LoginPage frame = new LoginPage();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void changePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordButtonActionPerformed
        
        String oldPassword = JOptionPane.showInputDialog(this, "Enter your old password: ", "Change password", JOptionPane.QUESTION_MESSAGE);
        String newPassword = JOptionPane.showInputDialog(this, "Enter your new password: ", "Change password", JOptionPane.QUESTION_MESSAGE);

        oldPassword = oldPassword.trim();
        newPassword = newPassword.trim();

        ResultPack<Boolean> r1 = UserController.changePassword(this.userDni, oldPassword, newPassword);

        if(r1.getOkay()) {
            JOptionPane.showMessageDialog(this, r1.getMessageFormatted(), "Change password", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(this, r1.getMessageFormatted(), "Change password", JOptionPane.ERROR_MESSAGE);
        }



    }//GEN-LAST:event_changePasswordButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPage().setVisible(true);
            }
        });
    }

    private Integer userDni;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton changePasswordButton;
    private javax.swing.JButton joinTeamButton;
    private javax.swing.JButton leaveTeamButton;
    private javax.swing.JButton myTeamsButton;
    private javax.swing.JButton transferButton;
    // End of variables declaration//GEN-END:variables
}
